version: '3.8'

services:
  index-tts:
    build: .
    image: index-tts-server
    env_file:
      - .env.example
    container_name: index-tts-server
    ports:
      - "${PORT:-8001}:${PORT:-8001}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
    #   - ./audio_prompts:/app/audio_prompts
      - ./assets:/app/assets
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8001}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
